# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "atlet99"
repo = "ztime_widget"

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
    - {{ commit.message | replace(from="[FEATURE] - ", to="") | replace(from="[FIX] - ", to="") | replace(from="[BUGFIX] - ", to="") | replace(from="[INIT] - ", to="") | replace(from="[ADD] - ", to="") | replace(from="[REFACTOR] - ", to="") | replace(from="[UPD] - ", to="") | replace(from="[CI] - ", to="") | replace(from="[LINT] - ", to="") | replace(from="[CHORE] - ", to="") | replace(from="[DOCS] - ", to="") | replace(from="[PERF] - ", to="") | replace(from="[STYLE] - ", to="") | replace(from="[TEST] - ", to="") | replace(from=";", to="") | trim | upper_first }}{% if commit.id %} ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }})){% endif %}
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/releases/tag/{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    {% if previous.version %}\
        ## [Unreleased]({{ self::remote_url() }}/compare/{{ previous.version }}...HEAD)
    {% else %}\
        ## [Unreleased]
    {% endif %}\
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}\
        {{ self::print_commit(commit=commit) }}\
    {% endfor -%}
{% endfor -%}

"""
footer = """
<!-- generated by git-cliff -->
"""
trim = true
postprocessors = []

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
    { message = "^\\[FEATURE\\]|^\\[ADD\\]|^\\[INIT\\]|^feat", group = "Features" },
    { message = "^\\[FIX\\]|^\\[BUGFIX\\]|^fix", group = "Bug Fixes" },
    { message = "^\\[REFACTOR\\]|^\\[UPD\\]|^refactor", group = "Refactor" },
    { message = "^\\[DOCS\\]|^doc", group = "Documentation" },
    { message = "^\\[PERF\\]|^perf", group = "Performance" },
    { message = "^\\[STYLE\\]|^style", group = "Styling" },
    { message = "^\\[TEST\\]|^test", group = "Testing" },
    { message = "^\\[CI\\]|^\\[LINT\\]|^\\[CHORE\\]|^chore|^ci|^build", group = "Miscellaneous Tasks" },
    { body = ".*security", group = "Security" },
    { message = "^revert", group = "Revert" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = "beta|alpha"
topo_order = false
sort_commits = "oldest"

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
initial_tag = "v1.0.0"
